spring.application.name=PlaceMentor
spring.datasource.url=jdbc:mysql://localhost:3306/placementor_db
spring.datasource.username=root
spring.datasource.password=Kavya@24

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
